const ALGORITHM_MANIFEST = [
  {
    id: "recursive-count",
    pattern: "single",
    language: "rust",
    title: "Recursive Count",
    signature: "fn conta(lista: &[i32]) -> i32",
    description: "Conta elementos de uma lista, um item por chamada.",
    complexity: "O(n)",
    engine: "algorithms/rust/recursive-count/engine.js",
    source: "algorithms/rust/recursive-count/source.rs",
  },
  {
    id: "factorial",
    pattern: "single",
    language: "rust",
    title: "Recursive Factorial",
    signature: "fn fat(x: u64) -> u64",
    description: "Multiplica até alcançar o caso base.",
    complexity: "O(n)",
    engine: "algorithms/rust/recursive-factorial/engine.js",
    source: "algorithms/rust/recursive-factorial/source.rs",
  },
  {
    id: "recursive-sum",
    pattern: "single",
    language: "rust",
    title: "Recursive Sum",
    signature: "fn soma(lista: &[i32]) -> i32",
    description: "Soma decompondo a lista em cabeça e resto.",
    complexity: "O(n)",
    engine: "algorithms/rust/recursive-sum/engine.js",
    source: "algorithms/rust/recursive-sum/source.rs",
  },
  {
    id: "call-stack",
    pattern: "none",
    language: "rust",
    title: "Call Stack",
    signature: "fn saudacao(nome: &str)",
    description: "Como uma chamada de função vira pilha, sem recursão ainda.",
    complexity: "sem recursão",
    engine: "algorithms/rust/call-stack/engine.js",
    source: "algorithms/rust/call-stack/source.rs",
  },
  {
    id: "max-element",
    pattern: "single",
    language: "rust",
    title: "Maximum Element",
    signature: "fn maior(lista: &[i32]) -> i32",
    description: "Encontra o maior elemento comparando sub-resultados.",
    complexity: "O(n)",
    engine: "algorithms/rust/max-element/engine.js",
    source: "algorithms/rust/max-element/source.rs",
  },
  {
    id: "binary-search",
    pattern: "single",
    language: "rust",
    title: "Recursive Binary Search",
    signature: "fn busca_binaria(lista: &[i32], alvo: i32) -> Option<usize>",
    description: "Divide o espaço de busca pela metade a cada chamada.",
    complexity: "O(log n)",
    engine: "algorithms/rust/binary-search/engine.js",
    source: "algorithms/rust/binary-search/source.rs",
  },
  {
    id: "fibonacci",
    pattern: "multiple",
    language: "rust",
    title: "Fibonacci (naive recursion)",
    signature: "fn fib(n: u64) -> u64",
    description: "Recursão dupla: cada chamada abre duas novas.",
    complexity: "O(2^n)",
    engine: "algorithms/rust/fibonacci/engine.js",
    source: "algorithms/rust/fibonacci/source.rs",
  },
  {
    id: "quicksort",
    pattern: "multiple",
    language: "rust",
    title: "Quicksort (Lomuto partition)",
    signature: "fn quicksort(lista: &mut Vec<i32>)",
    description: "Particiona a lista e recorre nos dois lados do pivô.",
    complexity: "O(n log n) médio",
    engine: "algorithms/rust/quicksort/engine.js",
    source: "algorithms/rust/quicksort/source.rs",
  },
];
